#libs####
set.seed(42)
options(nwarnings = 1000000)
summary(warnings(1000000))
dirLocal <- getwd()
dir.create(file.path(dirLocal, "rLib"), showWarnings = FALSE)
libLocal <- paste(dirLocal,"rLib",sep="/")
reposLib="http://cran.us.r-project.org"
library("infotheo", lib = libLocal)
library("jsonlite", lib = libLocal)
library("BiocManager", lib = libLocal)
library("BiocGenerics", lib = libLocal)
library("S4Vectors", lib = libLocal)
library("IRanges", lib = libLocal)
library("GenomeInfoDb", lib = libLocal)
library("Biobase", lib = libLocal)
library("matrixStats", lib = libLocal)
library("GenomicRanges", lib = libLocal)
library("MatrixGenerics", lib = libLocal)
library("SummarizedExperiment", lib = libLocal)
library("reshape2", lib = libLocal)
library("igraph", lib = libLocal)
library("limma", lib = libLocal)
library("lionessR", lib = libLocal)
#data####
M <- read.csv("dataGE.csv", header = T, row.names = 1)
dim(M)
#select####
sdM <- apply(as.array(as.matrix(M)), 1, sd)
muM <- apply(as.array(as.matrix(M)), 1, mean)
cvar <- sdM/muM
summary(cvar)
# https://github.com/orgs/community/discussions/26316 for plot , unblock cookies
hist(cvar)
dat <- cbind(cvar, M)
dat <- dat[order(dat[, 1], decreasing = F), ]
head(dat)
#dat <- dat[cvar>round(summary(cvar)[6]), -1]
dat <- dat[1:100, -1]
dat <- as.matrix(dat)
# dat <- as.matrix(M)
dim(dat)
hist(dat)
summary(dat)
#MI####
rN <- rownames(dat)
cN <- colnames(dat)
datDisc <- discretize(t(dat), disc = "equalwidth", nbins = 100)
summary(datDisc)
rownames(datDisc) <- cN
colnames(datDisc) <- rN
summary(datDisc)
hist(sapply(datDisc,as.numeric))
datDiscMI <- mutinformation(datDisc, method = "emp")
summary(datDiscMI)
hist(datDiscMI)
netFun <- function(x, ...) { mutinformation(discretize(t(x), disc = "equalwidth", nbins = 100), method = "emp")}
dim(datDisc)
cormat <- lioness(dat)
dim(cormat)
cData <- cormat@assays@data[[1]]
rownames(cData) <- rownames(cormat)
dim(cData)
head(cData)
hist(cData)
cData <- cData[abs(cData[, 3]) > 2, ]
hist(cData)
# https://github.com/mararie/lionessR/blob/master/vignettes/lionessR.Rmd
edgeCdata <- t(matrix(unlist(c(strsplit(row.names(cData), "_"))), 2))
# edgeCdata <- unlist(c(strsplit(row.names(cData), "_")))
tail(edgeCdata)
z <- cbind(edgeCdata, cData)
head(z)
plot(z[2,])
g <- graph.data.frame(z, directed = F)
plot(g)
dg <- igraph::degree(g)
sortDG <- sort.int(dg, decreasing = T, index.return = F)
max(sortDG)
min(sortDG)
plot(sortDG)
hist(sortDG)
head(sortDG, 25)
tail(sortDG, 25)
summary(warnings(1000000))
